apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ld-relay.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ld-relay.name" . }}
    helm.sh/chart: {{ include "ld-relay.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ld-relay.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ld-relay.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ if eq .Values.redis.enabled "true" }}
            - name: USE_REDIS
              value: "true"
{{ if eq .Values.redis.host "" }}
            - name: REDIS_HOST
              value: redis
{{ else }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
{{ end }}
{{ end }}
            - name: EXIT_ON_ERROR
              value: "true"
            - name: LD_ENV_PRODUCTION
              value: "{{ .Values.ldKey }}"
{{ if eq .Values.prometheus.enabled "true" }}
            - name: USE_PROMETHEUS
              value: "true"
{{ if eq .Values.prometheus.port"" }}
            - name: PROMETHEUS_PORT
              value: "9253"
{{ else }}
            - name: PROMETHEUS_PORT
              value: "{{ .Values.prometheus.port }}"
{{ end }}
{{ end }}
          ports:
            - name: http
              containerPort: 8030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8030
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
